default_connection_name = "myconnection"

[connections.myconnection]
account = "myaccount"
user = "myuser"
region = "us-east-1"
database = "mydatabase"
warehouse = "mywarehouse"
role = "myrole"
authenticator = "SNOWFLAKE_JWT"
private_key_file = "rsa_key.p8"